version: '3'  # version of compose format 

services:
  web:
    build: ./brevets
    command: python -u flask_brevets.py
    ports:
      - "5100:5100"
    volumes:
      - ./brevets:/app
    links:
      - db
  db:
    image: mongo:3.0.2

  acpbrevets-service:
    build: ./acpbrevets  
    volumes:
      - ./acpbrevets:/usr/src/app 
    ports:
      - 5102:80  # host:container
    depends_on:
      - web
  website:
    build: ./website 
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5101:80  # host:container
    depends_on:
      - acpbrevets-service  # website is not going to work unless acpbrevets-service is running
